### ISSUE TITLE
external "crypto":1 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by qld-cf** [yadPe/beatconnect_client#146]
hi @yadPe 
when i start the project,
`npm run dev`,
it occurs
Looking forward to your reply

**Comment by qld-cf** [comment]
in chrome, browser 
localhost: 3000

**Comment by yadPe** [comment]
Hi @qld-cf, thanks for your interest in the projet ! 

Because the bundle includes some nodeJs code, this error is normal when trying to use chrome to start the application.

The app is made to be executed with [electron](https://github.com/electron/electron).
`npm run dev` should start the webpack dev server and open electron. But It might not be that simple depending on the operating system you use. 

If you try executing `npm run electron-dev` what's the output ?

**Comment by qld-cf** [comment]
@yadPe yes, electron running normally
as you say, nothing can change the error if you use electron api in chrome
i got it and solve it
thanks
